CREATE TABLE TB_FORNECEDOR (
CD_FORNECEDOR     NUMBER(10,0) PRIMARY KEY
,NM_FORNECEDOR    VARCHAR(255) not null
,DS_EMAIL         VARCHAR(255) null
,DS_RAZAO_SOCIAL  VARCHAR(255) not null
,DS_CNPJ          VARCHAR(255) not null
);


CREATE SEQUENCE SEQ_FORNECEDOR
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;